#
# rcsid $Header: /usr/cvsroot/magic-7.5/irouter/Makefile,v 1.1.1.1 2006/04/10 22:03:14 tim Exp $
#

MODULE    = irouter
MAGICDIR  = ..
SRCS      = irCommand.c irMain.c irRoute.c irTestCmd.c irUtils.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
