#
# rcsid $Header: /usr/cvsroot/magic-7.5/wiring/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $
#

MODULE    = wiring
MAGICDIR  = ..
SRCS      = wireOps.c wireTech.c wireUndo.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
