#
# rcsid $Header: /usr/cvsroot/magic-7.5/textio/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $
#

MODULE    = textio
MAGICDIR  = ..
SRCS      = txCommands.c txInput.c txMain.c txMore.c txOutput.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
