#
# rcsid="$Header: /usr/cvsroot/magic-7.5/select/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $"
#

MODULE    = select
MAGICDIR  = ..
SRCS      = selCreate.c selDisplay.c selEnum.c selOps.c selUndo.c \
            selUnselect.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
