#
# rcsid $Header: /usr/cvsroot/magic-7.5/garouter/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $
#

MODULE    = garouter
MAGICDIR  = ..
SRCS      = gaChannel.c gaMain.c gaMaze.c gaSimple.c gaStem.c \
            gaTest.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
