#
# rcsid "$Header: /usr/cvsroot/magic-7.5/tiles/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $"
#

MODULE    = tiles
MAGICDIR  = ..
SRCS      = tile.c search.c search2.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
