#
# rcsid $Header: /usr/cvsroot/magic-7.5/plow/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $
#

MODULE    = plow
MAGICDIR  = ..
SRCS      = PlowCmd.c PlowJogs.c PlowMain.c PlowQueue.c PlowRandom.c \
            PlowRules1.c PlowRules2.c PlowRules3.c PlowSearch.c PlowTech.c \
            PlowTest.c PlowWidth.c PlowYank.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
