#
# rcsid $Header: /usr/cvsroot/magic-7.5/mzrouter/Makefile,v 1.1.1.1 2006/04/10 22:03:13 tim Exp $
#

MODULE    = mzrouter
MAGICDIR  = ..
SRCS      = mzBlock.c mzDebug.c mzEstimate.c mzXtndDown.c \
            mzXtndLeft.c mzXtndRght.c mzXtndUp.c mzHint.c mzInit.c mzNumLine.c \
            mzMain.c mzSearch.c mzStart.c mzSubrs.c mzTech.c mzTestCmd.c \
            mzWalk.c 

include ${MAGICDIR}/defs.mak
include ${MAGICDIR}/rules.mak
